version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: dev
  assignees:
  - dotvirus
  labels:
  - dependencies
  ignore:
  - dependency-name: "@babel/core"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.1
    - 7.13.10
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: rollup
    versions:
    - 2.38.1
    - 2.38.3
    - 2.38.4
    - 2.38.5
    - 2.39.0
    - 2.39.1
    - 2.40.0
    - 2.41.0
    - 2.41.1
    - 2.41.2
    - 2.41.3
    - 2.41.4
    - 2.41.5
    - 2.42.0
    - 2.42.2
    - 2.42.3
    - 2.45.1
    - 2.45.2
  - dependency-name: typedoc
    versions:
    - 0.20.19
    - 0.20.20
    - 0.20.23
    - 0.20.24
    - 0.20.25
    - 0.20.27
    - 0.20.28
    - 0.20.29
    - 0.20.30
    - 0.20.32
    - 0.20.33
    - 0.20.35
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.24
    - 14.14.25
    - 14.14.26
    - 14.14.28
    - 14.14.30
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.36
    - 14.14.39
    - 14.14.41
  - dependency-name: chai
    versions:
    - 4.3.0
    - 4.3.1
    - 4.3.3
  - dependency-name: uglify-js
    versions:
    - 3.12.5
    - 3.12.6
    - 3.12.7
    - 3.12.8
    - 3.13.0
    - 3.13.1
    - 3.13.2
    - 3.13.3
    - 3.13.4
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
  - dependency-name: eslint-config-prettier
    versions:
    - 7.2.0
    - 8.0.0
    - 8.2.0
  - dependency-name: "@types/chai"
    versions:
    - 4.2.15
    - 4.2.16
  - dependency-name: typescript
    versions:
    - 4.0.6
    - 4.0.7
    - 4.2.4
  - dependency-name: "@babel/cli"
    versions:
    - 7.12.13
    - 7.13.10
    - 7.13.14
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.13
    - 7.13.10
    - 7.13.12
    - 7.13.15
  - dependency-name: "@types/mocha"
    versions:
    - 8.2.1
    - 8.2.2
  - dependency-name: mocha
    versions:
    - 8.3.2
